name: 3hustlers
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - pip:
    - openai==0.26.1
    - SQLAlchemy==1.4.46
    - Flask-SQLAlchemy==3.0.2
    - python-dotenv==0.21.0
    - python-decouple==3.7
    - youtube-transcript-api==0.5.0
    - Flask==2.2.2
    - validators==0.20.0
    - Flask-JWT-Extended==4.2.3
