version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "article-scraper-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wqprejx0rdo7"
s3_prefix = "article-scraper-stack"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
